/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_ocrengineinit_free(a: number): void;
export function ocrengineinit_new(): number;
export function ocrengineinit_setDetectionModel(a: number, b: number, c: number, d: number): void;
export function ocrengineinit_setRecognitionModel(a: number, b: number, c: number, d: number): void;
export function __wbg_ocrengine_free(a: number): void;
export function ocrengine_new(a: number, b: number): void;
export function ocrengine_loadImage(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function ocrengine_detectText(a: number, b: number, c: number): void;
export function ocrengine_recognizeText(a: number, b: number, c: number, d: number, e: number): void;
export function ocrengine_getText(a: number, b: number, c: number): void;
export function ocrengine_getTextLines(a: number, b: number, c: number): void;
export function __wbg_image_free(a: number): void;
export function image_channels(a: number): number;
export function image_width(a: number): number;
export function image_height(a: number): number;
export function image_data(a: number, b: number): void;
export function __wbg_rotatedrect_free(a: number): void;
export function rotatedrect_corners(a: number, b: number): void;
export function rotatedrect_boundingRect(a: number, b: number): void;
export function __wbg_detectedline_free(a: number): void;
export function detectedline_rotatedRect(a: number): number;
export function detectedline_words(a: number, b: number): void;
export function __wbg_textword_free(a: number): void;
export function textword_text(a: number, b: number): void;
export function textword_rotatedRect(a: number): number;
export function __wbg_textline_free(a: number): void;
export function textline_text(a: number, b: number): void;
export function textline_words(a: number, b: number): void;
export const __wbindgen_export_0: WebAssembly.Table;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __externref_table_dealloc(a: number): void;
export function __externref_drop_slice(a: number, b: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __externref_table_alloc(): number;
export function __wbindgen_start(): void;
